#!/bin/bash


# jiangsu
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_changzhou.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_dafeng.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_huaian.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_lianyungang.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_nanjing.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_nantong.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_shuyang.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_suqian.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_suzhou.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_taizhou.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_wuxi.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_xuzhou.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_yancheng.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_yangzhou.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_zhenjiang.py

python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_changzhou_seller.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_dafeng_seller.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_huaian_seller.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_lianyungang_seller.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_nanjing_seller.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_nantong_seller.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_shuyang_seller.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_suqian_seller.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_suzhou_seller.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_taizhou_seller.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_wuxi_seller.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_xuzhou_seller.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_yancheng_seller.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_yangzhou_seller.py
python /data/python/spider/58_tc/sell_car/jiangsu/58_sell_car_zhenjiang_seller.py

# shanghai
python /data/python/spider/58_tc/sell_car/shanghai/58_sell_car_shanghai.py
python /data/python/spider/58_tc/sell_car/shanghai/58_sell_car_shanghai_seller.py

# anhui

python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_anqing.py 
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_anqing_seller.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_bengbu.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_bengbu_seller.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_bozhou.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_bozhou_seller.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_chaohu.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_chaohu_seller.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_chizhou.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_chizhou_seller.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_chuzhou.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_chuzhou_seller.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_fuyang.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_fuyang_seller.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_hexian.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_hexian_seller.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_hf.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_hf_seller.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_huaibei.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_huaibei_seller.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_huainan.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_huainan_seller.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_huangshan.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_huangshan_seller.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_huoqiu.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_huoqiu_seller.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_liuan.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_liuan_seller.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_maanshan.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_maanshan_seller.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_suzhou.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_suzhou_seller.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_tongcheng.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_tongcheng_seller.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_tongling.py
p#ython /data/python/spider/58_tc/sell_car/anhui/58_sell_car_tongling_seller.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_wuhu.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_wuhu_seller.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_xuancheng.py
python /data/python/spider/58_tc/sell_car/anhui/58_sell_car_xuancheng_seller.py


#shandong

python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_binzhou.py 
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_binzhou_seller.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_dezhou.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_dezhou_seller.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_dongying.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_dongying_seller.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_heze.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_heze_seller.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_jinan.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_jinan_seller.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_jining.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_jining_seller.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_kenli.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_kenli_seller.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_laiwu.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_laiwu_seller.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_liaocheng.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_liaocheng_seller.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_linyi.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_linyi_seller.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_qingdao.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_qingdao_seller.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_rizhao.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_rizhao_seller.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_taian.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_taian_seller.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_weifang.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_weifang_seller.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_weihai.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_weihai_seller.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_yantai.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_yantai_seller.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_zaozhuang.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_zaozhuang_seller.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_zhangqiu.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_zhangqiu_seller.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_zhucheng.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_zhucheng_seller.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_zibo.py
python /data/python/spider/58_tc/sell_car/shandong/58_sell_car_zibo_seller.py


# zhejiang
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_hangzhou.py  
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_hangzhou_seller.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_huzhou.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_huzhou_seller.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_jiaxing.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_jiaxing_seller.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_jinhua.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_jinhua_seller.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_lishui.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_lishui_seller.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_ningbo.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_ningbo_seller.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_quzhou.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_quzhou_seller.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_ruian.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_ruian_seller.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_shaoxing.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_shaoxing_seller.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_taizhou.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_taizhou_seller.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_wenzhou.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_wenzhou_seller.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_yiwu.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_yiwu_seller.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_yueqing.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_yueqing_seller.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_zhoushan.py
python /data/python/spider/58_tc/sell_car/zhejiang/58_sell_car_zhoushan_seller.py


